<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Lager et enkelt skrog som egen link med fast joint til base_link -->
  <xacro:macro name="trimaran_hull" params="parent length:=1.8 width:=0.9 height:=0.45">
    <link name="hull_link">
      <inertial>
        <mass value="50.0"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="2.0" iyy="2.0" izz="2.0" ixy="0" ixz="0" iyz="0"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height/10.0}"/>
        </geometry>
        <material name="hull_blue"><color rgba="0.1 0.2 0.7 1.0"/></material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height/10.0}"/>
        </geometry>
      </collision>
    </link>

    <joint name="hull_fixed" type="fixed">
      <parent link="${parent}"/>
      <child link="hull_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>
