oak:
  ros_parameters:
    camera:
      i_laser_dot_brightness: 0  # We may not need dot projection
      i_nn_type: yolo            # Hugr primus will be using Yolo for object detection
      i_tf_camera_model: ""
    pipeline_gen:
      i_enable_imu: false        # Hugr Primus uses XSENS IMU'
    left:
      i_fps: 30.0
      i_height: 720
      i_low_bandwidth: false     # This configuration expects high bandwidth
      i_publish_topic: true      # Allows the node to publish it's topics.
      i_resolution: 480P         # Sets the image quality to 720p for the publisher.
      i_width: 1280
    nn:
      i_enable_passthrough: true # neural network node passes though the topics it uses.
      i_enable_passthrough_depth: true
      i_num_inference_threads: 2 # Needs to be optimized
    rgb:
      i_enable_nn: true          # Allows Yolo to use this camera for inference.
      i_enable_preview: true     # idk what this does
      i_fps: 60.0                # The desired fps is 60 for responsiveness, may change to 50 if we need more processing power for Yolo.
      i_height: 720
      i_low_bandwidth: false
      i_publish_topic: true
      i_resolution: 720P
      i_width: 1280
    right:
      i_fps: 30.0
      i_height: 720
      i_low_bandwidth: false     # This configuration expects high bandwidth
      i_publish_topic: true      # Allows the node to publish it's topics.
      i_resolution: 480P         # Sets the image quality to 720p for the publisher.
      i_width: 1280
    stereo:
      i_low_bandwidth: false
