# hugr_ros2_control.yaml
controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    thruster_surge_front_controller:
      type: forward_command_controller/ForwardCommandController
      joints: [thruster_surge_front_joint]
      interface_name: position

    thruster_surge_rear_controller:
      type: forward_command_controller/ForwardCommandController
      joints: [thruster_surge_rear_joint]
      interface_name: position

    thruster_sway_port_controller:
      type: forward_command_controller/ForwardCommandController
      joints: [thruster_sway_port_joint]
      interface_name: position

    thruster_sway_starboard_controller:
      type: forward_command_controller/ForwardCommandController
      joints: [thruster_sway_starboard_joint]
      interface_name: position
