<?xml version="1.0"?>
<robot name="thruster_parts" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <material name="mat_thruster"><color rgba="0.2 0.2 0.3 1.0"/></material>

  <!-- axis: 'x' (default), 'y', or 'z'.  Cylinder is Z-aligned by default in URDF. -->
  <xacro:macro name="thruster"
               params="name parent
                       xyz:='0 0 0'
                       axis:='x'
                       diameter:=0.08
                       length:=0.12
                       mass:=0.8">

    <link name="${name}_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${diameter/2.0}" length="${length}"/></geometry>
        <material name="mat_thruster"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${diameter/2.0}" length="${length}"/></geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <!-- Cylinder inertia (axis along Z) -->
        <inertia ixx="${(mass*(3*(diameter/2.0)*(diameter/2.0)+length*length))/12.0}"
                 iyy="${(mass*(3*(diameter/2.0)*(diameter/2.0)+length*length))/12.0}"
                 izz="${0.5*mass*(diameter/2.0)*(diameter/2.0)}"
                 ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <!-- Compute orientation so the cylinder aligns with requested axis -->
    <!-- OrientÃ©r sylinder (URDF sylinder peker langs Z som standard) -->
    <xacro:property name="thr_roll"  value="${ (-pi/2.0) if axis == 'y' else 0.0 }"/>
    <xacro:property name="thr_pitch" value="${ ( pi/2.0) if axis == 'x' else 0.0 }"/>
    <xacro:property name="thr_yaw"   value="${ 0.0 }"/>

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent}"/>
      <child  link="${name}_link"/>
      <origin xyz="${xyz}" rpy="${thr_roll} ${thr_pitch} ${thr_yaw}"/>
    </joint>
  </xacro:macro>
</robot>
