FROM ros:humble-ros-base

ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

# Basic tools
RUN apt-get update && \
    apt-get install -y \
        locales \
        curl gnupg2 lsb-release build-essential \
        python3-pip git wget \
        python3-colcon-common-extensions \
        python3-vcstool \
        python3-rosdep \
        os-humble-ament-cmake \
    && locale-gen en_US en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

# rosdep already initialized in base image, but safe to update
RUN rosdep update

# Auto-source ROS
RUN echo "source /opt/ros/humble/setup.bash" >> /etc/bash.bashrc

WORKDIR /workspace

