name: ROS2 CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build & Test ROS2 workspace
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble   # or iron, jazzy, etc.
          colcon-defaults: |
            {
              "build": {
                "symlink-install": true
              }
            }
          vcs-repo-file-url: ""        # optional if you use .repos files
